# main text of home
name: Alexandru Somai
bio: Software Developer

# twitter summary info
description: My personal web space  

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://alexsomai.com
enforce_ssl: alexsomai.com

permalink: /blog/:title/

# if you have a custom blog url, this will override the default /blog
blog_url: https://medium.com/coders-do-read

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-87387171-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: alex_somai
#google: mygoogle
#instagram: myinstagram
#pinterest: mypinterest
linkedin: alexsomai
#youtube: myyoutube
#spotify: myspotify
github: alexsomai
#stackoverflow: 7044681/mystackoverflow
#quora: userquora
#reddit: username
medium: alexsomai
#vimeo: myvimeo
email: somai.alexandru@gmail.com

authors:
    alexsomai:
        name: Alexandru Somai
        bio: Software Developer
        external-image: false
        picture: assets/images/profile.jpg
        twitter: alex_somai

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
#paginate: 5
#paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below and rename projects.temp to projects.html
projects: false

# if you don't need "about" or "blog", comment them out below
# don't forget to rename about.temp to about.md and blog/index.temp to blog/index.html
about: false
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
#  - jekyll-feed

jekyll-mentions:
    base_url: https://github.com
